### ISSUE TITLE
DEFAULT_LAB seems to have no effect

### ISSUE THREAD

**Issue by thoraxe** [osevg/workshopper#9]
Using the following:

`WORKSHOPS_URLS=”https://gist.githubusercontent.com/marekjelen/a4339ab8d6b31d1174c754ad83f2129f/raw/02c29ae2fa5217c847a03ec7e79fde7641b18989/workshop.yml"`

And setting `DEFAULT_LAB=roadshow` seems to have no effect. I still have the list of labs and have to select roadshow.

**Comment by marekjelen** [comment]
The feature was missing. However, to do it, I had to update your yaml definition to add

```yaml
id: roadshow
```

so that the system does not generate the hash. And as we had the definition in a gist, there seems to be no way to get stable URL for latest version of raw gist content, I have moved your definition to [osevg/workshopper-workshops](https://github.com/osevg/workshopper-workshops) repo, please update your URL to 

```
https://raw.githubusercontent.com/osevg/workshopper-workshops/master/roadshow.yml
```
